### ISSUE TITLE
Possible nil pointer when not running etcd

### ISSUE THREAD

**Issue by crufter** [m3o/dev#300]
I titled it 'possible' as it might happen in my branch only (don't think so).
Repro: https://gist.github.com/crufter/5350512d0c02e07ba11749f3b62b8244

Result:

```
{"level":"warn","ts":"2020-07-30T11:14:57.268+0200","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-32b54d28-1f9f-45be-aafc-52eba122dd82/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10e3a6c]
goroutine 182 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/micro/micro/v3/service/debug/server.(*cached).services(0x0, 0x0, 0x0, 0x0)
	/home/crufter/code/src/github.com/micro/micro/service/debug/server/cache.go:37 +0x3c
github.com/micro/micro/v3/service/debug/stats/handler.(*Stats).scrape(0xc0002cc4e0)
	/home/crufter/code/src/github.com/micro/micro/service/debug/stats/handler/handler.go:109 +0x40
github.com/micro/micro/v3/service/debug/stats/handler.(*Stats).Start.func1(0xc000438480, 0xc0002cc4e0)
	/home/crufter/code/src/github.com/micro/micro/service/debug/stats/handler/handler.go:100 +0x2d
created by github.com/micro/micro/v3/service/debug/stats/handler.(*Stats).Start
	/home/crufter/code/src/github.com/micro/micro/service/debug/stats/handler/handler.go:94 +0x49
```

**Comment by domwong** [comment]
can't repro on current master
